<div class="row g-3">
    <div class="col-md-4"><label class="form-label" for="sku">SKU</label><input class="form-control" id="sku" name="sku" value="{{ old('sku', $product->sku ?? '') }}" required></div>
    <div class="col-md-8"><label class="form-label" for="name">Nombre</label><input class="form-control" id="name" name="name" value="{{ old('name', $product->name ?? '') }}" required></div>
    <div class="col-12"><label class="form-label" for="description">Descripción</label><textarea class="form-control" id="description" name="description" rows="2">{{ old('description', $product->description ?? '') }}</textarea></div>
    <div class="col-md-4"><label class="form-label" for="category_id">Categoría</label><select class="form-select" id="category_id" name="category_id" required>@foreach($categories as $category)<option value="{{ $category->id }}" @selected((string) old('category_id', $product->category_id ?? '') === (string) $category->id)>{{ $category->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label" for="unit_id">Unidad</label><select class="form-select" id="unit_id" name="unit_id" required>@foreach($units as $unit)<option value="{{ $unit->id }}" @selected((string) old('unit_id', $product->unit_id ?? '') === (string) $unit->id)>{{ $unit->name }} ({{ $unit->code }})</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label" for="tax_rate_id">Impuesto</label><select class="form-select" id="tax_rate_id" name="tax_rate_id" required>@foreach($taxRates as $taxRate)<option value="{{ $taxRate->id }}" @selected((string) old('tax_rate_id', $product->tax_rate_id ?? '') === (string) $taxRate->id)>{{ $taxRate->name }} ({{ $taxRate->rate_percent }}%)</option>@endforeach</select></div>
    <div class="col-md-3"><label class="form-label" for="min_stock">Stock mínimo</label><input type="number" step="0.001" min="0" class="form-control" id="min_stock" name="min_stock" value="{{ old('min_stock', $product->min_stock ?? 0) }}" required></div>
    <div class="col-md-3"><label class="form-label" for="max_stock">Stock máximo</label><input type="number" step="0.001" min="0" class="form-control" id="max_stock" name="max_stock" value="{{ old('max_stock', $product->max_stock ?? '') }}"></div>
    <div class="col-md-6 d-flex align-items-end"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" value="1" id="is_active" name="is_active" {{ old('is_active', $product->is_active ?? true) ? 'checked' : '' }}><label class="form-check-label" for="is_active">Activo</label></div></div>
</div>
<div class="mt-3"><button class="btn btn-primary" type="submit">Guardar</button> <a class="btn btn-secondary" href="{{ route('master-data.products.index') }}">Cancelar</a></div>
